export const inventory = [
  {
    name: 'Playstation 5 Console',
    description: 'lorem ipsum',
    sku: 'ps5-001',
    price: 449.0,
    img1: 'PS5-1',
    img2: 'PS5-2',
    img3: 'PS5-3',
    basket: 2,
  },
  {
    name: 'Playstation 5 Digital Edition Console',
    description: 'lorem ipsum',
    sku: 'ps5-002',
    price: 359.99,
    img1: 'PS5-DE-1',
    img2: 'PS5-DE-2',
    img3: 'PS5-DE-3',
    basket: 0,
  },
  {
    name: 'Xbox Series X',
    description: 'lorem ipsum',
    sku: 'xbx-001',
    price: 449.99,
    img1: 'Series-X-1',
    img2: 'Series-X-2',
    img3: 'Series-X-3',
    basket: 0,
  },
  {
    name: 'Xbox Series S',
    description: 'lorem ipsum',
    sku: 'xbx-002',
    price: 249.99,
    img1: 'Series-S-1',
    img2: 'Series-S-2',
    img3: 'Series-S-3',
    basket: 0,
  },
  {
    name: 'Nintendo Switch',
    description: 'lorem ipsum',
    sku: 'ntd-001',
    price: 279.99,
    img1: 'Switch-1',
    img2: 'Switch-2',
    img3: 'Switch-3',
    basket: 0,
  },
];
